### ISSUE TITLE
AttributeError: 'NoneType' object has no attribute 'lower'

### ISSUE THREAD

**Issue by AstraLuma** [duckinator/bork#345]
```
astraluma@nandi ~/code/ppb/pursuedpybear cirrus-changes @ bork build
Traceback (most recent call last):
  File "/home/astraluma/.local/bin/bork", line 5, in <module>
    from bork.cli import main
  File "/home/astraluma/.local/pipx/venvs/bork/lib64/python3.12/site-packages/bork/cli.py", line 24, in <module>
    from . import api
  File "/home/astraluma/.local/pipx/venvs/bork/lib64/python3.12/site-packages/bork/api.py", line 17, in <module>
    'pypi': pypi.Downloader('pypi'),
            ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/astraluma/.local/pipx/venvs/bork/lib64/python3.12/site-packages/bork/pypi.py", line 27, in __init__
    self.repository_url = self._download_url(repository_name)
                          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/astraluma/.local/pipx/venvs/bork/lib64/python3.12/site-packages/bork/pypi.py", line 41, in _download_url
    repo_config = config.get(repository_name, None)
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib64/python3.12/configparser.py", line 765, in get
    option = self.optionxform(option)
             ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib64/python3.12/configparser.py", line 853, in optionxform
    return optionstr.lower()
           ^^^^^^^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'lower'
```

**Comment by AstraLuma** [comment]
Looks like it works locally.

**Comment by duckinator** [comment]
@AstraLuma what version of Python do you use locally? I suspect it's a Python 3.12 API change.

**Comment by duckinator** [comment]
The more I dig into this, the more I'm confused I get.

First, I'm confused why it's breaking _now_, because:

- The implementation of ConfigParser's `get()` hasn't been touched in 13 years: https://github.com/python/cpython/blame/main/Lib/configparser.py#L695-L730 (only a few lines of the docstring were touched last year.)
- `optionxform()` hasn't been touched in 23 years: https://github.com/python/cpython/blame/ac4b44266d61651aea5928ce7d3fae4de226f83d/Lib/configparser.py#L804-L805

And second I'm confused because... `bork build` shouldn't be interacting with this part of the codebase, yet it clearly is. I think this boils down to how and where `bork.api.DOWNLOAD_SOURCES` is defined. It might make sense to move that definition `bork.api.download()`.
